server:  port: ${PORT:0}
spring:
  application:
    name: netflix-serieseureka:  client:    service-url:      #defaultZone: http://netflix-eureka-server:8761/eureka #Esta url aponta para o container docker      defaultZone: ${URL_EUREKA_SERVER:http://localhost:8761/eureka}  instance:    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}