version: "3.9"
services:
    
    db-netflix-user:
        image: postgres:12-alpine
        container_name: netflix-user-pg12
        ports:
        - "5432:5432"
        networks:
        - 76aoj-netflix-net
        environment:
        - POSTGRES_DB=db_netflix_user
        - POSTGRES_PASSWORD=root
        mem_limit: 512m

    db-netflix-category:
        image: postgres:12-alpine
        container_name: netflix-category-pg12
        ports:
        - "5433:5432"
        networks:
        - 76aoj-netflix-net
        environment:
        - POSTGRES_DB=db_netflix_category
        - POSTGRES_PASSWORD=root
        mem_limit: 512m

    db-netflix-movies:
        image: postgres:12-alpine
        container_name: netflix-movies-pg12
        ports:
        - "5434:5432"
        networks:
        - 76aoj-netflix-net
        environment:
        - POSTGRES_DB=db_netflix_movies
        - POSTGRES_PASSWORD=root
        mem_limit: 512m

    db-netflix-series:
        image: postgres:12-alpine
        container_name: netflix-series-pg12
        ports:
        - "5435:5432"
        networks:
        - 76aoj-netflix-net
        environment:
        - POSTGRES_DB=db_netflix_series
        - POSTGRES_PASSWORD=root
        mem_limit: 512m

    db-netflix-help-desk:
        image: postgres:12-alpine
        container_name: netflix-help-desk-pg12
        ports:
        - "5436:5432"
        networks:
        - 76aoj-netflix-net
        environment:
        - POSTGRES_DB=db_netflix_help_desk
        - POSTGRES_PASSWORD=root
        mem_limit: 512m
    
    netflix-zookeeper:        
        image: wurstmeister/zookeeper
        container_name: netflix-zookeeper
        ports:
        - "2181:2181"
        networks:
        - 76aoj-netflix-net
    netflix-kafka:        
        image: wurstmeister/kafka
        container_name: netflix-kafka
        ports:
        - "9092:9092"
        networks:
        - 76aoj-netflix-net
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
            KAFKA_ZOOKEEPER_CONNECT: netflix-zookeeper:2181

networks:
  76aoj-netflix-net:
    driver: bridge