server:  port: ${PORT:0}
spring:
  application:
    name: netflix-movieseureka:  client:    service-url:      #defaultZone: http://localhost:8761/eureka      defaultZone: http://netflix-eureka-server:8761/eureka #Esta url estar apontando para o container docker  instance:    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}