
INSERT INTO tb_user (NAME, EMAIL, PASSWORD, STATUS) VALUES ('Siron Azevedo', 'siron@fiap.com', '$2a$10$z6wj8DpUw4mK3QFWJLi97e4YLsS8G/okSzRwMZzA9IudWJjibc4By', 'ACTIVE');

INSERT INTO tb_role (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO tb_role (NAME) VALUES ('ROLE_USER');

INSERT INTO tb_user_role VALUES (1, 1);