server:
  port: 8765

spring:
  application:
    name: netflix-gateway

eureka:
  client:
    service-url:
      #defaultZone: http://netflix-eureka-server:8761/eureka #Esta url aponta para o container docker
      defaultZone: ${URL_EUREKA_SERVER:http://localhost:8761/eureka}
      
zuul:  routes:    category:
      service-id: netflix-category
      path: /netflix-category/**
    movies:
      service-id: netflix-movies
      path: /netflix-movies/**
    series:
      service-id: netflix-series
      path: /netflix-series/**
    user:
      service-id: netflix-user
      path: /netflix-user/**
    help-desk:
      service-id: netflix-help-desk
      path: /netflix-help-desk/**
    authorization:
      service-id: netflix-authorization
      path: /netflix-authorization/**
      sensitive-headers: Cookie,Set-Cookie
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000