server:
  port: 8765

spring:
  application:
    name: netflix-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
zuul:  routes:    category:
      service-id: netflix-category
      path: /netflix-category/**
    movies:
      service-id: netflix-movies
      path: /netflix-movies/**
    user:
      service-id: netflix-user
      path: /netflix-user/**
    authorization:
      service-id: netflix-authorization
      path: /netflix-authorization/**
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000